In [33]:
import pandas as pd
import numpy as np

In [34]:
data = {
    "EmpID": ["E101", "E102", "E103", "E104", "E105"],
    "Name": ["Atul", "Raj", "Darpan", "Anmol", "Piyush"],
    "Age": [25, 30, 23, 22, 32],
    "Designation": ["Manager", "Clerk", "Analyst", "Clerk", "Manager"],
    "Salary": [56000, 25000, 35000, 28000, 58000],
    "Bonus": [15000, 7000, 9000, 13000, 12000]
}

In [35]:
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
   EmpID    Name  Age Designation  Salary  Bonus
0  E101    Atul   25     Manager   56000  15000
1  E102     Raj   30       Clerk   25000   7000
2  E103  Darpan   23     Analyst   35000   9000
3  E104   Anmol   22       Clerk   28000  13000
4  E105  Piyush   32     Manager   58000  12000

In [36]:
new_row = pd.DataFrame([{
    "EmpID": "E106",
    "Name": "GEET",
    "Age": 25,
    "Designation": "Analyst",
    "Salary": 70000,
    "Bonus": 15000
}])

In [37]:
df = pd.concat([df, new_row], ignore_index=True)
print(df)

  EmpID    Name  Age Designation  Salary  Bonus
0  E101    Atul   25     Manager   56000  15000
1  E102     Raj   30       Clerk   25000   7000
2  E103  Darpan   23     Analyst   35000   9000
3  E104   Anmol   22       Clerk   28000  13000
4  E105  Piyush   32     Manager   58000  12000
5  E106    GEET   25     Analyst   70000  15000

In [38]:
# b) Add column "Shift" with "Morning"
df["Shift"] = "Morning"

In [39]:
# c) Print details of youngest employee
youngest = df[df["Age"] == df["Age"].min()]
print("\nYoungest Employee:\n", youngest)

Youngest Employee:
   EmpID   Name  Age Designation  Salary  Bonus    Shift
3  E104  Anmol   22       Clerk   28000  13000  Morning

In [40]:
# d) Print details of all clerks
clerks = df[df["Designation"] == "Clerk"]
print("\nAll Clerks:\n", clerks)

All Clerks:
   EmpID   Name  Age Designation  Salary  Bonus    Shift
1  E102    Raj   30       Clerk   25000   7000  Morning
3  E104  Anmol   22       Clerk   28000  13000  Morning

In [41]:
# e) Print average Bonus
avg_bonus = df["Bonus"].mean()
print("Average Bonus:", avg_bonus)

Average Bonus: 11833.333333333334

In [42]:
# f) Print total salary distributed
total_salary = df["Salary"].sum()
print("Total Salary Distributed:", total_salary)

Total Salary Distributed: 272000

In [43]:
# g) Add column "City"
cities = ["Janak Puri", "Tilak Nagar", "Shiv Nagar", "Vikas Puri", "Janak Puri", "Tilak Nagar"]
df["City"] = cities

In [44]:
# h) Delete record with EmpID 'E103' and 'E105'
df = df[~df["EmpID"].isin(["E103", "E105"])]

In [45]:
# i) Rename column "Bonus" as "Incentive"
df = df.rename(columns={"Bonus": "Incentive"})

In [46]:
print("\nFinal DataFrame:\n", df)

Final DataFrame:
   EmpID   Name  Age Designation  Salary  Incentive    Shift         City
0  E101   Atul   25     Manager   56000      15000  Morning   Janak Puri
1  E102    Raj   30       Clerk   25000       7000  Morning  Tilak Nagar
3  E104  Anmol   22       Clerk   28000      13000  Morning   Vikas Puri
5  E106   GEET   25     Analyst   70000      15000  Morning  Tilak Nagar

#Stationery DataFrame

In [47]:
data = {
    "Count": [15, 20, 25, 35],
    "Price": [250, 200, 600, 900]
}
index = ["Pencil", "Pen", "Eraser", "Scale"]

In [48]:
df = pd.DataFrame(data, index=index)
print("Original DataFrame:\n", df)

Original DataFrame:
         Count  Price
Pencil     15    250
Pen        20    200
Eraser     25    600
Scale      35    900

In [49]:
# a) Change the Eraser count to 15 instead of 25
df.loc["Eraser", "Count"] = 15
print(df)

        Count  Price
Pencil     15    250
Pen        20    200
Eraser     15    600
Scale      35    900

In [50]:
# b) Rename the index "Scale" as "Wooden Scale"
df = df.rename(index={"Scale": "Wooden Scale"})
print(df)

              Count  Price
Pencil           15    250
Pen              20    200
Eraser           15    600
Wooden Scale     35    900

In [51]:
# c) Change all row labels to Product 1, Product 2, Product 3, Product 4
df.index = ["Product 1", "Product 2", "Product 3", "Product 4"]
print(df)

           Count  Price
Product 1     15    250
Product 2     20    200
Product 3     15    600
Product 4     35    900

In [52]:
# d) Change all column names as "Discount", "Total"
df.columns = ["Discount", "Total"]
print(df)

           Discount  Total
Product 1        15    250
Product 2        20    200
Product 3        15    600
Product 4        35    900

In [53]:
# e) Add one row "Product 5" with value 10 and 100
df.loc["Product 5"] = [10, 100]
print(df)

           Discount  Total
Product 1        15    250
Product 2        20    200
Product 3        15    600
Product 4        35    900
Product 5        10    100

In [54]:
Products = df.drop(columns=["Total"])
print(Products)

           Discount
Product 1        15
Product 2        20
Product 3        15
Product 4        35
Product 5        10

#State-wise Production Data

In [55]:
data2 = {
    "Fruits": [44, 11950, 7152, 140169, 7830, 113],
    "Pulses": [23, 818, 33, 3184, 931, 1],
    "Rice": [814, 1930, 11586, 13574, 7452, 2604],
    "Wheat": [5, 2737, 16440, 30056, np.nan, np.nan]
}

states = ["Tripura", "Gujrat", "Punjab", "UP", "AP", "Kerala"]

In [56]:
df2 = pd.DataFrame(data2, index=states)
print("\nProduction DataFrame:\n", df2)

Production DataFrame:
          Fruits  Pulses   Rice    Wheat
Tripura      44      23    814      5.0
Gujrat    11950     818   1930   2737.0
Punjab     7152      33  11586  16440.0
UP       140169    3184  13574  30056.0
AP         7830     931   7452      NaN
Kerala      113       1   2604      NaN

In [57]:
# a) Total production for each state
total_per_state = df2.sum(axis=1)
print("\nTotal production for each state:\n", total_per_state)

Total production for each state:
 Tripura       886.0
Gujrat      17435.0
Punjab      35211.0
UP         186983.0
AP          16213.0
Kerala       2718.0
dtype: float64

In [58]:
# b) Total production for each item type
total_per_item = df2.sum(axis=0)
print("\nTotal production for each item type:\n", total_per_item)

Total production for each item type:
 Fruits    167258.0
Pulses      4990.0
Rice       37960.0
Wheat      49238.0
dtype: float64

In [59]:
# c) How many states produce Wheat? (non-NaN values)
wheat_states = df2["Wheat"].count()
print("\nNumber of states producing Wheat:", wheat_states)

Number of states producing Wheat: 4

# Series questions

In [62]:
#Q1
Series1 = pd.Series([100,200,300,400,500], index=["A","B","C","D","E"])
Series2 = Series1 * 2
Series2

A     200
B     400
C     600
D     800
E    1000
dtype: int64

Q2
a) False
b) True

In [64]:
#Q3
s = pd.Series(700, index=[200,201,202,203,204])
print(s)

200    700
201    700
202    700
203    700
204    700
dtype: int64

In [66]:
#Q4
sIP = pd.Series([89,92,95], index=["Physics","Chemistry","Math"])
print(sIP)
print(sIP + 10)

Physics      89
Chemistry    92
Math         95
dtype: int64
Physics       99
Chemistry    102
Math         105
dtype: int64

In [68]:
#Q5
SQTR = pd.Series([50000,65890,56780,89000,77900],
                 index=["QTR1","QTR2","QTR3","QTR4","QTR5"])
print(SQTR)

QTR1    50000
QTR2    65890
QTR3    56780
QTR4    89000
QTR5    77900
dtype: int64

In [69]:
#Q6
S1 = pd.Series([31,41,51])

print(S1 > 40)     # Statement 1
print(S1[S1 > 40]) # Statement 2

0    False
1     True
2     True
dtype: bool
1    41
2    51
dtype: int64

In [71]:
#Q7
S1 = pd.Series([39,41,42,44], index=["A","B","C","D"])
S2 = pd.Series([10,10,10,10], index=["A","B","D","F"])
print(S1[:2] * 100)
print(S1 * S2)
print(S2[::-1] * 10)

A    3900
B    4100
dtype: int64
A    390.0
B    410.0
C      NaN
D    440.0
F      NaN
dtype: float64
F    100
D    100
B    100
A    100
dtype: int64

In [74]:
#Q8
S1 = pd.Series([10,20,30,40], index=["A","B","C","D"])
S2 = pd.Series([5,4,6,8], index=["A","B","C","D"])

S1 * S2

A     50
B     80
C    180
D    320
dtype: int64

In [73]:
#Q9
s = pd.Series([75,78,82,86], index=["ENGLISH","HINDI","MATHS","SCIENCE"])

In [78]:
#Q10
company = pd.Series([350,200,800,150], index=["TCS","Reliance","L&T","Wipro"])
print(company[company > 250])
company.name = "Profit"
print(company)

TCS    350
L&T    800
dtype: int64
TCS         350
Reliance    200
L&T         800
Wipro       150
Name: Profit, dtype: int64

In [79]:
#Q11
a = [10,20,25,50]
b = pd.Series([10,20,25,50])

print(a*2)   # list repeats
print(b*2)   # series multiplies

[10, 20, 25, 50, 10, 20, 25, 50]
0     20
1     40
2     50
3    100
dtype: int64

In [80]:
#Q12
#ans a) print(Sample.tail(3))

In [81]:
#Q13
s = pd.Series(6, index=range(0,5))
print(s)

0    6
1    6
2    6
3    6
4    6
dtype: int64

In [83]:
s = pd.Series(np.arange(10,50,10))
print(s)
print(s.ndim)
print(s.shape)
print(len(s))

0    10
1    20
2    30
3    40
dtype: int64
1
(4,)
4

In [84]:
#Q16
s = pd.Series(np.random.randint(10, 21, 10))
print(s)

0    14
1    20
2    13
3    20
4    17
5    19
6    16
7    10
8    20
9    12
dtype: int64

In [85]:
data = {'one':'a','two':'b','three':'c'}
s = pd.Series(data)
print(s)
print(s.size)

one      a
two      b
three    c
dtype: object
3

In [87]:
S1 = pd.Series([2,4,6,8])
S1

0    2
1    4
2    6
3    8
dtype: int64

In [88]:
s2 = pd.Series(["i","am","a","student"])
print(s2)

0          i
1         am
2          a
3    student
dtype: object